# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 977b1b853e681152377debb1ff9b68593e145304aacb405368f27b27dcdb363d1c82b7c4ce9fc3e8cc77f9376b719ea5b61bee386b34d6820fd1ba4b52f7b73f

test:
  secret_key_base: 12fee449ae552f66121fa91a4549d255e17632b51427057187eafe92717d9ac6e210e8c435d8b619f81d6830ebfbedf450ba495027fcf80565dd69af0bd79d3c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
